/*
 * Сервис по обмену вещами Steam
 *
 * API for exchanging virtual items
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path once you place this file into your project.
	// For example,
	//
	//    sw "github.com/tolseone/go-server/go"
	//
	"go-server/internal/models/itemModel"
	"go-server/internal/models/tradeModel"
	"go-server/internal/models/userModel"
	"go-server/internal/routers"
	"go-server/internal/storage"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

func main() {
	db, err := gorm.Open(sqlite.Open("storage/test.db"), &gorm.Config{})
	if err != nil {
		log.Fatal(err)
	}

	db.AutoMigrate(&item.Item{}, &trade.Trade{}, &user.User{})

	repository := storage.NewSQLiteRepository(db)

	log.Printf("Server started")

	router := router.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
