/*
 * Сервис по обмену вещами Steam
 *
 * API for exchanging virtual items
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path once you place this file into your project.
	// For example,
	//
	//    sw "github.com/tolseone/go-server/go"
	//
	"go-server/internal/routers"
)

func main() {
	log.Printf("Server started")

	router := router.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
