/*
 * Сервис по обмену вещами Steam
 *
 * API for exchanging virtual items
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package item

type Item struct {
	ItemId      string `json:"item_id"`
	Name        string `json:"name"`
	Rarity      string `json:"rarity"`
	Description string `json:"description,omitempty"`
}

type Items struct {
	Items []Item `json:"items"`
}
