/*
 * Сервис по обмену вещами Steam
 *
 * API for exchanging virtual items
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type User struct {
	// Уникальный идентификатор пользователя
	UserId int32 `json:"user_id"`
	// Имя пользователя
	Username string `json:"username,omitempty"`
	// Адрес электронной почты пользователя
	Email string `json:"email"`
}

type Users struct {
	Users []User `json:"users"`
}
