/*
 * Сервис по обмену вещами Steam
 *
 * API for exchanging virtual items
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Item struct {

	ItemId string `json:"item_id"`

	Name string `json:"name"`
	// Редкость предмета
	Rarity string `json:"rarity"`
	// Описание предмета
	Description string `json:"description,omitempty"`
}
