/*
 * Сервис по обмену вещами Steam
 *
 * API for exchanging virtual items
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Trade struct {
	TradeId       string `json:"trade_id"`
	Status        string `json:"status,omitempty"`
	OfferedItem   *Item  `json:"offered_item,omitempty"`
	RequestedItem *Item  `json:"requested_item,omitempty"`
}

type Trades struct {
	Trades []Trade `json:"trades"`
}
